[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "2.0", features = ["serde"] }

wireguard-control = { path = "../../innernet/wireguard-control" }
ipnet = "2.11.0"
clap = { version = "4.5.40", features = ["derive"] }
